### ISSUE TITLE
doesn't contain a constructor which accepts 0 arguments.

### ISSUE THREAD

**Issue by pilotdave** [NovanMK2/UnrealLibNoise#1]
doesn't work on 4.19

ERROR:c:\Users\David\Documents\UnrealProjects\infini\Plugins\UnrealLibNoise\Source\UnrealLibNoise\UnrealLibNoise.Build.cs(7,9) : error CS1729: 'UnrealBuildTool.ModuleRules' doesn't contain a constructor which accepts 0 arguments.
ERROR: UnrealBuildTool Exception: Unable to compile source files.

i get this error when i'm starting up the project containing this plugin or when generating project files.

**Comment by pilotdave** [comment]
Fixed it with
https://answers.unrealengine.com/questions/764146/unreal-build-tool-error-1.html
